---
# Based on https://wiki.evolveum.com/display/midPoint/Installing+midPoint+from+Binary+Distribution+v2.2
#    - tomcat.yml
- hosts: all
  gather_facts: False
  sudo: yes
  vars:
    # midpoint_download: http://www.evolveum.com/downloads/midpoint/2.2/midpoint-2.2.tar.gz
    midpoint_archive: sources/midpoint-2.2.1-dist.zip
    midpoint_war: sources/midpoint-2.2.1/war/midpoint.war  
    midpoint_home: "/opt/midpoint"
  tasks:
    - name: install python selinux libs
      yum: pkg={{ item }}
      with_items:
       - libselinux-python

    - name: install midpoint prerequisites 
      yum: pkg={{ item }}
      with_items:
       - unzip.x86_64
       - java-1.7.0-openjdk.x86_64
       - tomcat6 
       - tomcat6-webapps 
       - tomcat6-admin-webapps

    - name: calm down selinux
      selinux: state=disabled

    - name: stop iptables to open port 8080
      action: service name=iptables state=stopped
      
    # - name: Download Midpoint archive
    #   shell: "wget -q -O '{{midpoint_archive}}' --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http://www.oracle.com/' '{{midpoint_download}}' creates='{{midpoint_archive}}' "

    - name: begin midpoint 
      file: dest={{midpoint_home}} state=directory
      sudo: no

    - name: deploy midpoint config
      unarchive: creates=/opt/midpoint/config.xml src={{midpoint_archive}} dest={{midpoint_home}}

    - name: deploy midpoint war
      copy: src={{midpoint_war}} dest=/var/lib/tomcat6/webapps/midpoint.war backup=yes force=yes

    - name: midpoint.war permissions
      file: dest=/var/lib/tomcat6/webapps/midpoint.war group=tomcat owner=tomcat

    - name: midpoint home exists 
      file: dest={{midpoint_home}} state=directory

    - name: start tomcat
      action: service name=tomcat6 state=started
