---
# Based on https://wiki.evolveum.com/display/midPoint/Installing+midPoint+from+Binary+Distribution+v2.2
#    - tomcat.yml
- hosts: all
  gather_facts: False
  sudo: yes
  vars:
    midpoint_root: /home/vagrant
    midpoint_download: http://www.evolveum.com/downloads/midpoint/2.2/midpoint-2.2.tar.gz
    midpoint_archive: sources/midpoint-2.2.1-dist.zip
    midpoint_war: /home/vagrant/midpoint-2.2/war/midpoint.war
    java_download: http://download.oracle.com/otn-pub/java/jdk/7u45-b18/jdk-7u45-linux-x64.tar.gz
    java_name: jdk1.7.0_45
    download_folder: /usr/src
    java_archive: "{{download_folder}}/{{java_name}}.tar.gz"
    java_folder: /usr/lib/jvm
    java_alias: java-7-oracle
  tasks:
    - name: install python selinux libs
      yum: pkg={{ item }}
      with_items:
       - libselinux-python

    - name: install midpoint prerequisites 
      yum: pkg={{ item }}
      with_items:
       - unzip.x86_64
       - java-1.7.0-openjdk.x86_64
       - tomcat6 
       - tomcat6-webapps 
       - tomcat6-admin-webapps

    - name: calm down selinux
      selinux: state=disabled

    - name: stop iptables to open port 8080
      action: service name=iptables state=stopped
      
    # - name: Download Midpoint archive
    #   shell: "wget -q -O '{{midpoint_archive}}' --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http://www.oracle.com/' '{{midpoint_download}}' creates='{{midpoint_archive}}' "

    - name: ensure isntall root exists
      file: dest={{midpoint_root}} state=directory

    - name: Extract Midpoint archive
      unarchive: creates={{midpoint_root}}/foo src={{midpoint_archive}} dest={{midpoint_root}}

    #- name: Set JAVA_OPTS
    #shell: echo "TODO: /link updated catalina.sh script from this deploy...add modified version to this deploy"

    - name: deploy midpoint
      file: state=link src={{midpoint_war}} dest=/tomcat/webapps/midpoint.war

    - name: start tomcat
      action: service name=tomcat6 state=started
